version: '3.5'

services:
  reverse-proxy:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"      
      - "8080:8080"
    volumes:
      - "./traefik.toml:/etc/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock"
  test:
    image: emilevauge/whoami
    labels:
      - traefik.frontend.rule=Host:whoami.docker.localhost
